### ISSUE TITLE
Memory access violation on windows x86_64 when linking to libpq > 9.6.5

### ISSUE THREAD

**Issue by ruomad** [lpsmith/postgresql-libpq#43]
Hello,
I get this error when linking to libpq-10.3 or libpq-9.6.8. (through postgresql-simple)
No problem with libpq-9.6.5
The error occurs when running a query.
Anyone has the same problem or an idea of what could be the source of this ?
It seems the same issue than https://github.com/lpsmith/postgresql-simple/issues/244
The interesting point is that it doesn't occur with versions below 9.6.5

**Comment by ruomad** [comment]
I built a small test which is quite conclusive, error happens in getvalue when trying to access the query result.

test program

```
{-# LANGUAGE OverloadedStrings #-}
module Main where

import Data.Maybe (isJust, fromJust)
import Database.PostgreSQL.LibPQ

main :: IO ()
main = do
  h <- connectdb "host=localhost port=5432 user=postgres dbname=postgres"
  v <- libpqVersion
  putStrLn $ show v
  r <- exec h "SELECT 1"
  if isJust r then do
    let r_ = fromJust r
    rs <- resultStatus r_
    putStrLn . show $ rs
    n <- ntuples r_
    putStrLn $ show n
    p <- nfields r_
    putStrLn $ show p
    nl <- mapM (getisnull r_ 0) [0..(p-1)]
    putStrLn $ show nl
    ll <- mapM (getlength r_ 0) [0..(p-1)]
    putStrLn $ show ll
    putStrLn $ show r_
    res <- mapM (getvalue r_ 0) [0..(p-1)]
    putStrLn $ show res
    else putStrLn "Empty"
  finish h`
```

When linking postgresql-libpq against libpq-9.6.5 yields

> 90605
TuplesOk
Row 1
Col 1
[False]
[1]
Result 0x000000000034b7c0
[Just "1"]

When linking against libpq-10.3 it yields

> 100003
TuplesOk
Row 1
Col 1
[False]
[1]
Result 0x000000000034a6c0
Access violation in generated code when executing data at 000000008000fb50

**Comment by ruomad** [comment]
I checked and there is no segfault when linked against libpq-9.6.8, so this is an issue for postgresql-10

**Comment by lpsmith** [comment]
Thank you for all the legwork, @roumad!
